language: python
sudo: false
branches:
  only:
  - master
python:
  - '3.5.1'
addons:
  postgresql: '9.4'
  apt:
    packages:
      - python3-enchant
services:
  - redis-server
install:
  - pip install --upgrade pip==8.1.1
  - pip install -qr requirements_test.txt
  - pip install --upgrade coveralls
before_script:
  - psql -c 'create database lunchtime;' -U postgres
script:
  - coverage run -m 'pytest'
after_success:
  - coveralls
